<?php

namespace ContainerMhx7bJs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EyLJki7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EyLJki7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EyLJki7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CommentController::create' => ['privates', '.service_locator.xQG.Mth', 'get_ServiceLocator_XQG_MthService', true],
            'App\\Controller\\CommentController::delete' => ['privates', '.service_locator.z0ViHeD', 'get_ServiceLocator_Z0ViHeDService', true],
            'App\\Controller\\ContactController::adminList' => ['privates', '.service_locator.APpTZ8d', 'get_ServiceLocator_APpTZ8dService', true],
            'App\\Controller\\ContactController::deletePost' => ['privates', '.service_locator.MCtSnIL', 'get_ServiceLocator_MCtSnILService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.d00XA5i', 'get_ServiceLocator_D00XA5iService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\PostController::adminList' => ['privates', '.service_locator.d00XA5i', 'get_ServiceLocator_D00XA5iService', true],
            'App\\Controller\\PostController::createPost' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PostController::deletePost' => ['privates', '.service_locator.xQG.Mth', 'get_ServiceLocator_XQG_MthService', true],
            'App\\Controller\\PostController::detail' => ['privates', '.service_locator.bMkWER5', 'get_ServiceLocator_BMkWER5Service', true],
            'App\\Controller\\PostController::editPost' => ['privates', '.service_locator.xQG.Mth', 'get_ServiceLocator_XQG_MthService', true],
            'App\\Controller\\PostController::index' => ['privates', '.service_locator.d00XA5i', 'get_ServiceLocator_D00XA5iService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.7hbcaRc', 'get_ServiceLocator_7hbcaRcService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.Jzrkv.y', 'get_ServiceLocator_Jzrkv_YService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CommentController:create' => ['privates', '.service_locator.xQG.Mth', 'get_ServiceLocator_XQG_MthService', true],
            'App\\Controller\\CommentController:delete' => ['privates', '.service_locator.z0ViHeD', 'get_ServiceLocator_Z0ViHeDService', true],
            'App\\Controller\\ContactController:adminList' => ['privates', '.service_locator.APpTZ8d', 'get_ServiceLocator_APpTZ8dService', true],
            'App\\Controller\\ContactController:deletePost' => ['privates', '.service_locator.MCtSnIL', 'get_ServiceLocator_MCtSnILService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.d00XA5i', 'get_ServiceLocator_D00XA5iService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\PostController:adminList' => ['privates', '.service_locator.d00XA5i', 'get_ServiceLocator_D00XA5iService', true],
            'App\\Controller\\PostController:createPost' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PostController:deletePost' => ['privates', '.service_locator.xQG.Mth', 'get_ServiceLocator_XQG_MthService', true],
            'App\\Controller\\PostController:detail' => ['privates', '.service_locator.bMkWER5', 'get_ServiceLocator_BMkWER5Service', true],
            'App\\Controller\\PostController:editPost' => ['privates', '.service_locator.xQG.Mth', 'get_ServiceLocator_XQG_MthService', true],
            'App\\Controller\\PostController:index' => ['privates', '.service_locator.d00XA5i', 'get_ServiceLocator_D00XA5iService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.7hbcaRc', 'get_ServiceLocator_7hbcaRcService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.Jzrkv.y', 'get_ServiceLocator_Jzrkv_YService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CommentController::create' => '?',
            'App\\Controller\\CommentController::delete' => '?',
            'App\\Controller\\ContactController::adminList' => '?',
            'App\\Controller\\ContactController::deletePost' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\PostController::adminList' => '?',
            'App\\Controller\\PostController::createPost' => '?',
            'App\\Controller\\PostController::deletePost' => '?',
            'App\\Controller\\PostController::detail' => '?',
            'App\\Controller\\PostController::editPost' => '?',
            'App\\Controller\\PostController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CommentController:create' => '?',
            'App\\Controller\\CommentController:delete' => '?',
            'App\\Controller\\ContactController:adminList' => '?',
            'App\\Controller\\ContactController:deletePost' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\PostController:adminList' => '?',
            'App\\Controller\\PostController:createPost' => '?',
            'App\\Controller\\PostController:deletePost' => '?',
            'App\\Controller\\PostController:detail' => '?',
            'App\\Controller\\PostController:editPost' => '?',
            'App\\Controller\\PostController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
