<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMhx7bJs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMhx7bJs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMhx7bJs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMhx7bJs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMhx7bJs\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mhx7bJs',
    'container.build_id' => 'c27ce05c',
    'container.build_time' => 1656880765,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMhx7bJs');
